Desktop page
LethaboMot/PORT pull request #3
Opened 2022-11-10 15:14 UTC by LethaboMot

In this project I:

-Added more images
- edit and added to HTML
- edit and added on CSS

2022-11-10 18:33 UTC, christianbiring1 requested changes
Hi @LethaboMot , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![163947610-e4d849d5-e69c-49b9-90bd-a4191f4e2856](https://user-images.githubusercontent.com/97100091/201176769-fa4e861c-6d34-4a04-bc8f-106813e5deb9.gif)


## Highlights
- [ ] Descriptive PR `title` and `summary`
- [ ] All linters checks are passing :heavy_check_mark: 
- [ ] Good commit history.

## Required Changes ♻️
- [ ] `KINDLY CONSIDER USING THE media-query TO STYLE HOW YOUR ELEMENTS WILL LOOK LIKE ON THE DESKTOP VERSION. IF YOU ARE NOT FAMILIAR WITH IT, IT'S TOTALLY FINE. YOU MAY CONSIDER CHECKING IT` [HERE](https://www.youtube.com/watch?v=yU7jJ3NbPdA&t=41s)
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Fixing your mobile version after you have applied media-query as you can see how it looks ugly 
![image](https://user-images.githubusercontent.com/97100091/201178101-3156e310-2172-4a81-a7da-6ea3aed4f8d2.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-10 18:33 UTC, christianbiring1 commented on style.css
> +
- [ ] Kindly consider using the media queries to style your page on desktop screens.
`Hint: If you do not have any clue how to do that. It's totally fine. You can check that` [here](https://www.youtube.com/watch?v=yU7jJ3NbPdA)`

Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/201174630-d5461656-f994-488a-a137-0b69d9472868.png)

Figma template :point_down: 
![image](https://user-images.githubusercontent.com/97100091/201174794-4106b55c-cd40-4f9a-9c2b-8cd33bbd8975.png)

2022-11-10 18:33 UTC, christianbiring1 commented on style.css
> +}
- [ ] Kindly make sure you stick to the design as much as possible, the spacing(margin, padding), typos are supposed to be similar to the design in Figma.
Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/201175790-00422f39-538a-48a1-a7a1-49a8e03c5754.png)

Figma template :point_down: 
![image](https://user-images.githubusercontent.com/97100091/201175996-1eca8174-535c-4ea6-a8e9-b47a61f556b6.png)

2022-11-10 18:33 UTC, christianbiring1 commented on style.css
> +.details {
- [ ] Kindly make sure you stick to the design as much as possible.

Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/201176460-69cf9f1e-05bf-48e6-afac-81c659e6308e.png)
![image](https://user-images.githubusercontent.com/97100091/201176519-809d7475-d4cf-4079-a5ca-0d69ee2f4a78.png)

Figma design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/201176264-c4b62786-6790-45ed-bce0-a287df24a9d3.png)
![image](https://user-images.githubusercontent.com/97100091/201176332-f1352568-710d-47b2-8fa6-8692259ac2b1.png)

2022-11-11 13:12 UTC, Nemwel-Boniface requested changes
## Hello @LethaboMot      :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Great job addressing some of the changes that were requested by a previous reviewer :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

- [ ] As requested by the previous reviewer, kindly ensure that you make use of media queries to ensure that you have both a desktop and a mobile version. **Note:** even though you were supposed to build the desktop version of your project, you are required to built on top of the mobile version by adding the media queries to now help you have the desktop version together with the media query.
- [ ] When you add the media query and have the mobile version as well in your project, your project will be ready for approval., 

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-11 13:12 UTC, Nemwel-Boniface commented on index.html
>      <section id="Introduction">
- [ ] I am not sure if this section added is supposed to be in your project. Is this an extension of the mobile version? it is supposed to be one markup but the styling is what will make it both mobile and desktop friendly.

2022-11-12 03:36 UTC, jerryowusu approved these changes
Hi @LethaboMot 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![power approve](https://user-images.githubusercontent.com/65233860/201454466-6e772aca-42b8-416d-8e1a-463c68f3b3a5.gif)


## Highlights
All linters are passing :heavy_check_mark: 
Good commit messages :heavy_check_mark: 
Followed GitHub flow :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-12 03:36 UTC, jerryowusu commented on style.css
> +  }
[OPTIONAL] Nice work implementing the media query. Unfortunately some of your images are not working as expected as shown  below. Kindly check and fix them.

![Screenshot from 2022-11-12 03-28-36](https://user-images.githubusercontent.com/65233860/201454424-5b54c251-286c-45e9-a603-f83baf9b6616.png)

![Screenshot from 2022-11-12 03-28-57](https://user-images.githubusercontent.com/65233860/201454427-e64dcba9-8e54-420c-b81e-4eeca5d70019.png)

![Screenshot from 2022-11-12 03-29-13](https://user-images.githubusercontent.com/65233860/201454432-65b3419a-e55c-4459-a7c6-73ef5b1e9b3f.png)

2022-11-12 07:24 UTC, merged